### ISSUE TITLE
Infinity Loader doesn't work with Bob's belts

### ISSUE THREAD

**Issue by hexagonhexagon** [raiguard/InfinityMode#1]
I get the following messages when I try to use an infinity loader with any of the Bob's belts:
```
Unable to identify belt type. Please report the following information to the mod author via GitHub or the Mod Portal:
belt_name='ultimate-transport-belt', parse_result='ultimate'
belt_name='turbo-transport-belt', parse_result='turbo'
belt_name='basic-transport-belt', parse_result='basic'
```

From what I can tell, this is a load order issue: what happens is that your mod loads first and you create the infinity loaders in the data phase, but then Bob's Logistics loads after yours and creates its belts in the data phase after yours, so you miss Bob's belts when you create the loaders.

Here is a snippet of my log that shows what is going on:
![image](https://user-images.githubusercontent.com/25755516/62736657-df8cfe80-b9fb-11e9-82af-067c042e3924.png)

**Comment by raiguard** [comment]
Huh, I tested Bob's belts and they appeared to work. I guess my game was loading them before. I'll try moving loader creation to data-updates. Thanks!

**Comment by raiguard** [comment]
Should be fixed for the next version!

**Comment by raiguard** [comment]
v0.2.0 is released.
