### ISSUE TITLE
Settings of infinity wagon are not saved in blueprint

### ISSUE THREAD

**Issue by Calibretto22** [raiguard/InfinityMode#10]
When creating a blueprint of a infinity wagon the settings of the wagon are not saved. 

When building the blueprint, the infinity wagon is placed without settings.

**Comment by raiguard** [comment]
This will be a bit tricky, since the infinity filters are saved in invisible non-interactable chests. I'll figure something out.

**Comment by Calibretto22** [comment]
for me it's not that important. 
imho: if the solution is performance intense better leave it as it is. perhaps write a warning into the tooltip or the readme. 

the good performance is more important for me than "feature completeness".

**Comment by raiguard** [comment]
It won't be performance intense, all I'll have to do is add an infinity chest for every wagon in the blueprint. It'll be complicated, but perfectly doable.

**Comment by raiguard** [comment]
In 0.17.67 they added the ability to store custom data in blueprints. That made it trivial to make wagons support blueprinting properly, so it's in for the next version!

![wagon blueprinting](https://user-images.githubusercontent.com/3515394/64405349-0ca0f100-d03c-11e9-8751-940619c28c49.gif)
