### ISSUE TITLE
Krastorio issues

### ISSUE THREAD

**Issue by AimMoreBetter** [raiguard/InfinityMode#11]
"Failed to load mods: Error while loading item prototype "super-productivity-module" (module): Key "limitation_message_key" not found in property tree at ROOT.module.super-productivity-module Modifications: Infinity Mode > Krastorio

**Comment by raiguard** [comment]
I am completely unable to reproduce this. What other mods do you have active?

**Comment by raiguard** [comment]
I reverse-engineered your bug report and implemented a potential fix, please let me know if it still crashes with v0.5.0.

**Comment by AimMoreBetter** [comment]
Yep it worked!

**Comment by raiguard** [comment]
Awesome!
