### ISSUE TITLE
Cheat mode is disabled on 0.17.67

### ISSUE THREAD

**Issue by ronakg** [raiguard/InfinityMode#12]
Suddenly auto-construction on blueprints is not working in 0.17.67. Was working fine in .66. I'm not able to enable it either as the check-boxes are disabled.

Screenshot -

[
<img width="341" alt="Screen Shot 2019-09-03 at 3 40 10 PM" src="https://user-images.githubusercontent.com/1058322/64213327-6dc09d00-ce61-11e9-9640-9d48d38e3e73.png">
](url)

**Comment by raiguard** [comment]
I replied to another report on this on the mod portal. This was a bug in vanilla, not Infinity Mode, and was fixed in 0.17.68. The checkboxes are disabled because you're in the map editor, which has its own versions of those cheats (which also broke and was fixed).
