### ISSUE TITLE
crash to menu after creating a new BP. 

### ISSUE THREAD

**Issue by Calibretto22** [raiguard/InfinityMode#14]
i got this erromessage: 

> The mod Infinity Mode caused a non-recoverable error.
> Please report this error to the mod author.
> 
> Error while running event InfinityMode::on_player_setup_blueprint (ID 68)
> LuaFluidBox API call when LuaFluidBox was invalid.
> stack traceback:
> 	[string "local n, v = "serpent", "0.30" -- (C) 2012-17..."]:71: in function 'val2str'
> 	[string "local n, v = "serpent", "0.30" -- (C) 2012-17..."]:95: in function 'val2str'
> 	[string "local n, v = "serpent", "0.30" -- (C) 2012-17..."]:95: in function 'val2str'
> 	[string "local n, v = "serpent", "0.30" -- (C) 2012-17..."]:119: in function <[string "local n, v = "serpent", "0.30" -- (C) 2012-17..."]:15>
> 	(...tail calls...)
> 	__InfinityMode__/scripts/infinity-wagon.lua:105: in function 'handler'
> 	__stdlib__/stdlib/event/event.lua:315: in function 'pcall'
> 	__stdlib__/stdlib/event/event.lua:335: in function 'dispatch_event'
> 	__stdlib__/stdlib/event/event.lua:413: in function <__stdlib__/stdlib/event/event.lua:369>
> stack traceback:
> 	[C]: in function '__len'
> 	[string "local n, v = "serpent", "0.30" -- (C) 2012-17..."]:71: in function 'val2str'
> 	[string "local n, v = "serpent", "0.30" -- (C) 2012-17..."]:95: in function 'val2str'
> 	[string "local n, v = "serpent", "0.30" -- (C) 2012-17..."]:95: in function 'val2str'
> 	[string "local n, v = "serpent", "0.30" -- (C) 2012-17..."]:119: in function <[string "local n, v = "serpent", "0.30" -- (C) 2012-17..."]:15>
> 	(...tail calls...)
> 	__InfinityMode__/scripts/infinity-wagon.lua:105: in function 'handler'
> 	__stdlib__/stdlib/event/event.lua:315: in function 'pcall'
> 	__stdlib__/stdlib/event/event.lua:335: in function 'dispatch_event'
> 	__stdlib__/stdlib/event/event.lua:413: in function <__stdlib__/stdlib/event/event.lua:369> 

i'll do some research. the number of the BP seems low - it could be an old one.

**Comment by Calibretto22** [comment]
it happens whenever i make a new BP. wether there are infinityitems included or not. 
i experienced crashes with 
- a slightly (QOL) modded savegame 
- after unloading all mods (except IM) in the same save 

the crashes did **not** occur 
- after disabling IM, saving the problematic savegame without IM, enabling IM and loading the save. 
- after starting a new game with only IM active. 
- after starting a new game with all my usual mods active

so i suspect some existing infinity-wagons (or blueprints) in the existing savegame.

**Comment by Calibretto22** [comment]
the error only happens after loading a savegame with an older version of IM.

**Comment by raiguard** [comment]
Fixed for the next version.

**Comment by raiguard** [comment]
v0.6.1 has been released.
