### ISSUE TITLE
Icon of "Infinity Pump" is "infinity pipe" in certain cases

### ISSUE THREAD

**Issue by Calibretto22** [raiguard/InfinityMode#18]
In certain cases the icon of "infinity pump" is replaced by the icon of "infinity pipe". 

This happens when the user: 
- selects or sets a filter in a deconstruction planner
- selects or sets a filter in a upgrade planner

this does not happen when: 
- creating a blueprint (neither in blueprint-icons nor the list of bluprint-items)
- setting filters in a cargo wagon
- setting filters in a logistic chest

example DeconPlanner: 
`0eNptj+sKgzAMhd8lvyvoJhP7KmMU0TjK2lTaOCbSd192Y8j2L/nOyeWsMGAfKHGce7aBzOQ6IoygV0jIbOmcHjUSW17MaB1jND4MCLpUWyzG4wrUedHA0mhJtGKyE4KSfsCbzGT1xzL76Wup8kkBR8RkOhpMDP0lmUBuAT12LqGI1uHPK0+Y0OErx5tnWcvo5do2Z/HJqeAqnwsB3ezLqq13dXNoc74Dh9RkWQ==`

![image](https://user-images.githubusercontent.com/29695655/68545654-5ce75700-03cf-11ea-86b9-effbb86d8cc3.png)
![image](https://user-images.githubusercontent.com/29695655/68545679-991ab780-03cf-11ea-96f6-bc223b85a536.png)

No Error: 
![image](https://user-images.githubusercontent.com/29695655/68545699-c2d3de80-03cf-11ea-9795-4f0f200d3277.png)

**Comment by raiguard** [comment]
Yeah, I noticed this and a few other ones when I was trying to fix a different bug a few days ago... it's fixed for the next release! Thanks for the report.

**Comment by raiguard** [comment]
v0.6.1 has been released.
