### ISSUE TITLE
Instant upgrade on loaders changes unloaders to loaders

### ISSUE THREAD

**Issue by LeonSkills** [raiguard/InfinityMode#21]
How to reproduce: remove the hidden tags from loader items.  
```
data.raw.item.loader.flags = {}
data.raw.item['fast-loader'].flags = {}
```
Place a loader as if it is unloading an entity. Use an upgrade planner to change it to an other loader. 

Result:
https://i.imgur.com/cV8cotM.mp4

The unloader swaps its belt and chest side, and becomes a dysfunctional loader.

**Comment by raiguard** [comment]
Thanks for the report. However, I am no longer going to be working on this mod. It is getting replaced with [Editor Extensions](https://github.com/raiguard/EditorExtensions), which will have all of the items and entities from this mod (plus a few more!), but will be centered around the map editor. The Map Editor has its own instant upgrading logic that doesn't have this problem.

The mod won't be released for a while, not until the map editor receives a few more features (such as hiding the editor GUI when you don't want to use it).

Sorry, and thanks again!
