### ISSUE TITLE
Factorio ExtendedPlus cant identify belt

### ISSUE THREAD

**Issue by ghost** [raiguard/InfinityMode#22]
https://imgur.com/a/tV7gZDk

Factorio ExtendedPlus 

mk1 - mk2 belts/undergrounds/splitters and deadlocks loaders are affected

**Comment by raiguard** [comment]
Thank you for the report, but I am no longer going to be updating Infinity Mode. Instead, it is getting replaced by [Editor Extensions](https://github.com/raiguard/EditorExtensions). EE will have all the items and entities from this mod (plus a few more!), but will not include the LUA cheats, instead being centered around the map editor. Alongside a few QoL improvements to the map editor in the near future, EE will make this mod redundant. Sorry!

I have fixed this for Editor Extensions' infinity loader, so when that mod releases, it won't have this issue. Thanks again!
