### ISSUE TITLE
Settings do not save and disabling mod permanently changes modifiers

### ISSUE THREAD

**Issue by itsthejoker** [raiguard/InfinityMode#3]
I have IM installed so that I can work out things in my test world and then move to my primary world. My movement speed is insane in my primary world, but changing the movement modifier to anything else has no effect and is reset to 2 as soon as I close the window. I would like to be able to disable IM on my primary world altogether, but I also do not see that as an option. 

After disabling IM and reloading my primary world, my inventory size and base speed are both completely screwed up. I'm really not sure what to do here because I don't have a backup of my world and the autosaves are for my test world. Are there some fields that I can change through the command line to reset everything?

I opened a thread on the mod page, but will close in favor of this.

**Comment by itsthejoker** [comment]
Update: found the issue. Clicking on a field, changing the value, and then _clicking out of it_ instead of hitting enter _appears_ to set the value, but it does not stick. I don't think this is a mod problem; seems like a factorio issue. Closing issue.

**Comment by raiguard** [comment]
You need to press enter after entering a number for it to register. I'll add something for the next version that will make sure people know this (it's a recent capability that was added just last week).

You are not the first one to request the ability to enable/disable the mod, so I'll add a popup like Creative Mode has. As for the speeds, re-enable Infinity Mode, open your primary world, and set all of the numbers in the 'bonuses' section of the player cheats to zero (more specifically, the running speed bonus). Save your world and re-disable the mod, and everything should work.

**Comment by raiguard** [comment]
Oh lol, we both commented at the same time. I asked the devs for the ability to confirm when clicking out of textfields, but they said it was impossible to do in a consistent way.

**Comment by itsthejoker** [comment]
Ah, okay. Thanks for following up, I appreciate it. Now that everything's set to zero, I'll just keep it how it is for now -- looking forward to using this more. Thanks for your help and work!
