### ISSUE TITLE
Crash: conflicting next_upgrade bounding boxes

### ISSUE THREAD

**Issue by AimMoreBetter** [raiguard/InfinityMode#5]
Failed to load mods: Error while running setup for entity prototype "infinity-chest-active-provider" (infinity-container): next_upgrade target (logistic-chest-active-provider-2) must have the same bounding box.

**Comment by AimMoreBetter** [comment]
All I can tell you is that by disabling Bob's logistics mod will allow it to load.

**Comment by zero318** [comment]
Seems to be because bob's mods add more tiers of logistic chest and the upgrade planner functionality of the basic logistic chests gets copied to the infinity chests. Setting chest.next_upgrade = nil in the prototype definition for the logistic chests should solve the problem.

**Comment by raiguard** [comment]
Hmm, this doesn't happen to me. I'll implement zero's suggestion and you'll have to let me know if it works.

**Comment by raiguard** [comment]
v0.2.2 is out, does it work now?

**Comment by AimMoreBetter** [comment]
I'm out at dinner right now but I'll check when I get back.

**Comment by AimMoreBetter** [comment]
Yes it worked, thank you!

**Comment by raiguard** [comment]
No problem!
