### ISSUE TITLE
Infinity Accumulator GUI Crash

### ISSUE THREAD

**Issue by zero318** [raiguard/InfinityMode#6]
Attempting to change the mode or priority of an infinity accumulator causes a crash with [this error](https://imgur.com/bLt8Hax).

Looks like the refresh_ia_gui function needs to be moved above the change_ia_mode_or_priority function in order to not resolve to nil.

**Comment by raiguard** [comment]
Aargh, should be fixed in 0.2.2. I think that's the record for the quickest back-to-back patches... ever.
