### ISSUE TITLE
Instant request doesn't work when items are manually trashed

### ISSUE THREAD

**Issue by hexagonhexagon** [raiguard/InfinityMode#7]
As is in the title. Steps to reproduce: 

1. Request anything.
1. Take the items you requested, and manually pick them up (so they are in your cursor stack).
1. Drop the items in the trash slots.

The requested items do not come back until you change the request amount. This same problem does not occur if you shift-click the items to the trash slots: that works as expected.

**Comment by raiguard** [comment]
Thanks for the report, this has been fixed for the next version.
