### ISSUE TITLE
Infinity personal roboport icon size wrong with Bob's Equipment mod

### ISSUE THREAD

**Issue by hexagonhexagon** [raiguard/InfinityMode#8]
See the picture below:

![image](https://user-images.githubusercontent.com/25755516/63193402-6153dc00-c03b-11e9-8837-4cd1b7ff23b0.png)

If Bob's equipment is present, it changes the icon of the personal roboport equipment to a different icon that is 64x64 in size instead of 32x32. Since in your "infinity-misc.lua" you set the icon_size of the infinity-personal-roboport-equipment to 32, this leads to the above situation. I think this could be easily resolved by changing the icon size to be data.raw['item']['personal-roboport-equipment'].icon_size.

**Comment by raiguard** [comment]
Thanks for the report, this has been fixed for the next version.
